# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'print_comp_lifts.ui'
#
# Created: Tue Dec 16 19:51:49 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_print_win(object):
    def setupUi(self, print_win):
        print_win.setObjectName("print_win")
        print_win.resize(800, 600)
        self.centralwidget = QtGui.QWidget(print_win)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 40, 701, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_cb = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.name_cb.setObjectName("name_cb")
        self.horizontalLayout.addWidget(self.name_cb)
        self.gender_cb = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.gender_cb.setObjectName("gender_cb")
        self.horizontalLayout.addWidget(self.gender_cb)
        self.group_cb = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.group_cb.setObjectName("group_cb")
        self.horizontalLayout.addWidget(self.group_cb)
        self.age_cb = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.age_cb.setObjectName("age_cb")
        self.horizontalLayout.addWidget(self.age_cb)
        self.bdy_weight_cb = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.bdy_weight_cb.setObjectName("bdy_weight_cb")
        self.horizontalLayout.addWidget(self.bdy_weight_cb)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lift_type_cb = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.lift_type_cb.setObjectName("lift_type_cb")
        self.horizontalLayout_3.addWidget(self.lift_type_cb)
        self.lift_name_cb = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.lift_name_cb.setObjectName("lift_name_cb")
        self.horizontalLayout_3.addWidget(self.lift_name_cb)
        self.lift_wt_cb = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.lift_wt_cb.setObjectName("lift_wt_cb")
        self.horizontalLayout_3.addWidget(self.lift_wt_cb)
        self.group_cb_2 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.group_cb_2.setObjectName("group_cb_2")
        self.horizontalLayout_3.addWidget(self.group_cb_2)
        self.year_cb = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.year_cb.setObjectName("year_cb")
        self.horizontalLayout_3.addWidget(self.year_cb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comp_yearEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.comp_yearEdit.setObjectName("comp_yearEdit")
        self.horizontalLayout_2.addWidget(self.comp_yearEdit)
        self.lift_name_box = QtGui.QComboBox(self.verticalLayoutWidget)
        self.lift_name_box.setObjectName("lift_name_box")
        self.horizontalLayout_2.addWidget(self.lift_name_box)
        self.fromYearEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.fromYearEdit.setObjectName("fromYearEdit")
        self.horizontalLayout_2.addWidget(self.fromYearEdit)
        self.toYearEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.toYearEdit.setObjectName("toYearEdit")
        self.horizontalLayout_2.addWidget(self.toYearEdit)
        self.filter_btn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.filter_btn.setObjectName("filter_btn")
        self.horizontalLayout_2.addWidget(self.filter_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableView = QtGui.QTableView(self.verticalLayoutWidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        print_win.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(print_win)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        print_win.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(print_win)
        self.statusbar.setObjectName("statusbar")
        print_win.setStatusBar(self.statusbar)

        self.retranslateUi(print_win)
        QtCore.QMetaObject.connectSlotsByName(print_win)

    def retranslateUi(self, print_win):
        print_win.setWindowTitle(QtGui.QApplication.translate("print_win", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.name_cb.setText(QtGui.QApplication.translate("print_win", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.gender_cb.setText(QtGui.QApplication.translate("print_win", "Gender", None, QtGui.QApplication.UnicodeUTF8))
        self.group_cb.setText(QtGui.QApplication.translate("print_win", "Group", None, QtGui.QApplication.UnicodeUTF8))
        self.age_cb.setText(QtGui.QApplication.translate("print_win", "Age", None, QtGui.QApplication.UnicodeUTF8))
        self.bdy_weight_cb.setText(QtGui.QApplication.translate("print_win", "Body Weight", None, QtGui.QApplication.UnicodeUTF8))
        self.lift_type_cb.setText(QtGui.QApplication.translate("print_win", "Lift Type", None, QtGui.QApplication.UnicodeUTF8))
        self.lift_name_cb.setText(QtGui.QApplication.translate("print_win", "Lift Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lift_wt_cb.setText(QtGui.QApplication.translate("print_win", "Lift Weight", None, QtGui.QApplication.UnicodeUTF8))
        self.group_cb_2.setText(QtGui.QApplication.translate("print_win", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.year_cb.setText(QtGui.QApplication.translate("print_win", "Year", None, QtGui.QApplication.UnicodeUTF8))
        self.comp_yearEdit.setPlaceholderText(QtGui.QApplication.translate("print_win", "Competition Year", None, QtGui.QApplication.UnicodeUTF8))
        self.fromYearEdit.setPlaceholderText(QtGui.QApplication.translate("print_win", "From Year", None, QtGui.QApplication.UnicodeUTF8))
        self.toYearEdit.setPlaceholderText(QtGui.QApplication.translate("print_win", "To Year", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_btn.setText(QtGui.QApplication.translate("print_win", "Filter", None, QtGui.QApplication.UnicodeUTF8))

